---

- hosts: all
  become: true
  tasks:
  - name: install httpd and php packages for CentOS servers
    yum:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
  - name: install apache and php for Ubuntu Servers
    yum:
      name: 
        - libapache2-mod-php
        - apache2
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
